server:
  port: 8080

spring:
  application:
    name: gestao-setor-api

  flyway:
    enabled: false

  datasource:
    url: jdbc:h2:mem:gestaodb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update