server:
  port: 8080

spring:
  application:
    name: gestao-setor-api

  flyway:
    enabled: false

  datasource:
    url: jdbc:mysql://localhost:3306/SystemTI?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: Unimed@2026!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  mail:
    host: smtp-mail.outlook.com
    port: 587
    username: avisos@unimedvarginha.coop.br
    password: ${DB_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

api:
  security:
    token:
      secret: unimed-ti-dev-secret-123

